module.exports = {
  FIND_CUSTOM_FIELD_BY_ID_ERROR: {
    code: "FIND_CUSTOM_FIELD_BY_ID_ERROR",
    message: "Finding custom field by ID failed with exception"
  },

  FIND_CUSTOM_FIELD_BY_ALIAS_ERROR: {
    code: "FIND_CUSTOM_FIELD_BY_ALIAS_ERROR",
    message: "Finding custom field by Alias failed with exception"
  },

  FIND_CUSTOM_FIELD_VALUE_BY_ID_ERROR: {
    code: "FIND_CUSTOM_FIELD_VALUE_BY_ID_ERROR",
    message: "Finding custom field value by ID failed with exception"
  },

  FIND_CUSTOM_FIELD_VALUE_BY_ALIAS_ERROR: {
    code: "FIND_CUSTOM_FIELD_VALUE_BY_ALIAS_ERROR",
    message: "Finding custom field value by Alias failed with exception"
  },

  SET_CUSTOM_FIELD_VALUE_ERROR: {
    code: "SET_CUSTOM_FIELD_VALUE_ERROR",
    message: "Setting custom field value failed with exception"
  },

  LOAD_CUSTOM_FIELD_BY_ALIAS_ERROR: {
    code: "LOAD_CUSTOM_FIELD_BY_ALIAS_ERROR",
    message: "Loading custom field by alias failed with exception"
  },

  ENSURE_CUSTOM_FIELDS_EXIST_POSSIBLE_ERROR: {
    code: "ENSURE_CUSTOM_FIELDS_EXIST_POSSIBLE_ERROR",
    message: "Creating custom fields might have failed with exception"
  },

  ENSURE_ONE_CUSTOM_FIELD_EXIST_ERROR: {
    code: "ENSURE_ONE_CUSTOM_FIELD_EXIST_ERROR",
    message: "Creating one custom field failed with exception"
  },

  ENSURE_CUSTOM_FIELDS_EXIST_ERROR: {
    code: "ENSURE_CUSTOM_FIELDS_EXIST_ERROR",
    message: "Creating custom fields failed with exception"
  },

  LOAD_UPSALES_APP_CONFIG_ERROR: {
    code: "LOAD_UPSALES_APP_CONFIG_ERROR",
    message: "Getting app config from Upsales failed"
  },

  SAVE_UPSALES_APP_CONFIG_ERROR: {
    code: "SAVE_UPSALES_APP_CONFIG_ERROR",
    message: "Saving app config at Upsales failed"
  },

  UPDATE_UPSALES_APP_CONFIG_ERROR: {
    code: "UPDATE_UPSALES_APP_CONFIG_ERROR",
    message: "Updating fields in app config at Upsales failed"
  },

  SET_UPSALES_CLIENT_PARAM_ERROR: {
    code: "SET_UPSALES_CLIENT_PARAM_ERROR",
    message: "Some error has occured while setting Upsales client parameter"
  },

  UPSALES_GET_CURRENCIES_ERROR: {
    code: "UPSALES_GET_CURRENCIES_ERROR",
    message: "Some error has occured while getting Upsales currencies"
  },

  FIND_MASTER_CURRENCY_ERROR: {
    code: "FIND_MASTER_CURRENCY_ERROR",
    message:
      "Some error has occured while searching for master currency among all the currencies"
  },

  UPSALES_GET_MASTER_CURRENCY_ERROR: {
    code: "UPSALES_GET_MASTER_CURRENCY_ERROR",
    message:
      "Some error has occured while acquiring master currency from Upsales"
  },

  UPSALES_UI_SEND_PROGRESS_ERROR: {
    code: "UPSALES_UI_SEND_PROGRESS_ERROR",
    message: "Some error has occured while sending progress to Upsales UI"
  },

  UPSALES_UI_SEND_ERROR_ERROR: {
    code: "UPSALES_UI_SEND_ERROR_ERROR",
    message: "Some error has occured while sending Error message to Upsales UI"
  },

  UPSALES_UI_SEND_MESSAGE_ERROR: {
    code: "UPSALES_UI_SEND_MESSAGE_ERROR",
    message: "Some error has occured while sending message to Upsales UI"
  },

  UPSALES_CREATE_DYNAMIC_LINK_ERROR: {
    code: "UPSALES_CREATE_DYNAMIC_LINK_ERROR",
    message: "Dynamic link creation at Upsales failed with error"
  },

  UPSALES_LOAD_DYNAMIC_LINK_ERROR: {
    code: "UPSALES_LOAD_DYNAMIC_LINK_ERROR",
    message: "Dynamic links retrieving at Upsales failed with error"
  },

  UPSALES_IS_DYNAMIC_LINK_EXIST_ERROR: {
    code: "UPSALES_IS_DYNAMIC_LINK_EXIST_ERROR",
    message:
      "Some error has occured while checking Upsales dynamic link existance"
  },

  UPSALES_CREATE_DYNAMIC_LINK_IF_NECESSARY_ERROR: {
    code: "UPSALES_CREATE_DYNAMIC_LINK_IF_NECESSARY_ERROR",
    message:
      "Dynamic link existance checking and creation at Upsales failed with error"
  },

  LOAD_ENTITY_FIELDS_ERROR: {
    code: "LOAD_ENTITY_FIELDS_ERROR",
    message: "Unexpected loading entity fields error"
  },

  SEND_UPSALES_EXTERNAL_APP_HOOK_ERROR: {
    code: "SEND_UPSALES_EXTERNAL_APP_HOOK_ERROR",
    message: "Calling Upsales external hook failed unexpectedly"
  }
};
